import { Permission } from '../types/authorization';
import { OrganizationRole, PlatformRole } from '../types/auth';

export type AppRoleCode = PlatformRole | OrganizationRole;

/**
 * Matriz imutável de permissões por perfil (Princípio do Menor Privilégio)
 */
export const ROLE_PERMISSIONS_MATRIX: Readonly<Record<AppRoleCode, readonly Permission[]>> = {
  // Superadministrador da plataforma (Escopo Global)
  platform_super_admin: [
    'platform:view_overview',
    'platform:view_organizations',
    'platform:view_audit',
    'platform:manage_governance',
    'audit:view_platform',
    'personal_account:view_profile',
    'personal_account:manage_preferences',
  ],

  // Proprietário da organização (Governança e Supervisão Plena)
  owner: [
    'organization:view_overview',
    'organization:view_settings',
    'organization:manage_settings',
    'organization:manage_governance',
    'users_and_access:view',
    'users_and_access:manage',
    'users_and_access:manage_roles',
    'clients:view',
    'clients:create',
    'clients:edit',
    'client_capturer_assignments:view',
    'client_capturer_assignments:manage',
    'properties:view',
    'properties:create',
    'properties:edit',
    'properties:geospatial:view',
    'properties:geospatial:edit',
    // Módulo 004: Governança e Supervisão
    'appraisals:view',
    'appraisal_requests:view_queue',
    'appraisal_requests:assign',
    'technical_professionals:verify',
    'technical_professionals:manage_capabilities',
    // Módulo 005: Pipeline Comercial Completo
    'proposals:view',
    'proposals:view_financials',
    'proposals:create',
    'proposals:edit_draft',
    'proposals:submit',
    'proposals:assign_review',
    'proposals:approve',
    'proposals:present',
    'proposals:record_decision',
    'proposals:cancel',
    'proposals:view_document',
    'proposals:issue_document',
    'proposals:view_commercial_tracking',
    'proposals:manage_follow_up',
    'proposals:view_handoff',
    'proposals:prepare_handoff',
    'proposals:view_handoff_queue',
    'proposals:acknowledge_handoff',
    'proposals:renew',
    // Outros módulos
    'documents:view',
    'documents:upload',
    'documents:download',
    'documents:register_reference',
    'documents:manage',
    'documents:view_requirements',
    'documents:fulfill_requirements',
    'documents:review_requirements',
    'documents:manage_requirements',
    'documents:manage_validity',
    'documents:share',
    'documents:export',
    'surveys_and_visits:view',
    'surveys_and_visits:schedule',
    'surveys_and_visits:execute',
    'schedule:view',
    'schedule:manage',
    'fleet:view',
    'fleet:manage',
    'finance:view_overview',
    'finance:view_records',
    'finance:manage_operations',
    'audit:view_organization',
    'personal_account:view_profile',
    'personal_account:manage_preferences',
  ],

  // Administrador da empresa (Operação cotidiana da empresa)
  company_admin: [
    'organization:view_overview',
    'organization:view_settings',
    'organization:manage_settings',
    'users_and_access:view',
    'users_and_access:manage',
    'clients:view',
    'clients:create',
    'clients:edit',
    'client_capturer_assignments:view',
    'client_capturer_assignments:manage',
    'properties:view',
    'properties:create',
    'properties:edit',
    'properties:geospatial:view',
    'properties:geospatial:edit',
    // Módulo 004: Gestão Operacional e Atribuição
    'appraisals:view',
    'appraisal_requests:view_queue',
    'appraisal_requests:assign',
    'technical_professionals:verify',
    'technical_professionals:manage_capabilities',
    // Módulo 005: Pipeline Comercial Completo
    'proposals:view',
    'proposals:view_financials',
    'proposals:create',
    'proposals:edit_draft',
    'proposals:submit',
    'proposals:assign_review',
    'proposals:approve',
    'proposals:present',
    'proposals:record_decision',
    'proposals:cancel',
    'proposals:view_document',
    'proposals:issue_document',
    'proposals:view_commercial_tracking',
    'proposals:manage_follow_up',
    'proposals:view_handoff',
    'proposals:prepare_handoff',
    'proposals:view_handoff_queue',
    'proposals:acknowledge_handoff',
    'proposals:renew',
    // Outros módulos
    'documents:view',
    'documents:upload',
    'documents:download',
    'documents:register_reference',
    'documents:manage',
    'documents:view_requirements',
    'documents:fulfill_requirements',
    'documents:review_requirements',
    'documents:manage_requirements',
    'documents:manage_validity',
    'documents:share',
    'documents:export',
    'surveys_and_visits:view',
    'surveys_and_visits:schedule',
    'surveys_and_visits:execute',
    'schedule:view',
    'schedule:manage',
    'fleet:view',
    'fleet:manage',
    'finance:view_overview',
    'finance:view_records',
    'personal_account:view_profile',
    'personal_account:manage_preferences',
  ],

  // Gerente (Coordenação operacional, agenda e equipe)
  manager: [
    'organization:view_overview',
    'users_and_access:view',
    'clients:view',
    'clients:create',
    'clients:edit',
    'client_capturer_assignments:view',
    'client_capturer_assignments:manage',
    'properties:view',
    'properties:create',
    'properties:edit',
    'properties:geospatial:view',
    'properties:geospatial:edit',
    // Módulo 004: Fila, Atribuição e Homologação
    'appraisals:view',
    'appraisal_requests:view_queue',
    'appraisal_requests:assign',
    'technical_professionals:verify',
    // Módulo 005: Coordenação e Aprovação Comercial
    'proposals:view',
    'proposals:view_financials',
    'proposals:create',
    'proposals:edit_draft',
    'proposals:submit',
    'proposals:assign_review',
    'proposals:approve',
    'proposals:present',
    'proposals:record_decision',
    'proposals:cancel',
    'proposals:view_document',
    'proposals:issue_document',
    'proposals:view_commercial_tracking',
    'proposals:manage_follow_up',
    'proposals:view_handoff',
    'proposals:prepare_handoff',
    'proposals:view_handoff_queue',
    'proposals:acknowledge_handoff',
    'proposals:renew',
    // Outros módulos
    'documents:view',
    'documents:upload',
    'documents:download',
    'documents:register_reference',
    'documents:manage',
    'documents:view_requirements',
    'documents:fulfill_requirements',
    'documents:review_requirements',
    'documents:manage_requirements',
    'documents:manage_validity',
    'documents:share',
    'documents:export',
    'surveys_and_visits:view',
    'surveys_and_visits:schedule',
    'surveys_and_visits:execute',
    'schedule:view',
    'schedule:manage',
    'fleet:view',
    'fleet:manage',
    'personal_account:view_profile',
    'personal_account:manage_preferences',
  ],

  // Projetista (Elaboração agronômica, laudos e propostas)
  project_designer: [
    'organization:view_overview',
    'clients:view',
    'client_capturer_assignments:view',
    'properties:view',
    'properties:create',
    'properties:edit',
    'properties:geospatial:view',
    'properties:geospatial:edit',
    // Módulo 004: Laudos e Solicitações Atribuídas
    'appraisals:view',
    'appraisals:view_assigned',
    'appraisals:create',
    'appraisals:edit',
    'appraisals:edit_assigned',
    'appraisals:review',
    'appraisals:issue',
    'appraisal_requests:view_assigned',
    'technical_professionals:view_self',
    'technical_professionals:update_self',
    // Módulo 005: Revisão técnica estritamente atribuída
    'proposals:view',
    'proposals:view_assigned',
    'proposals:view_financials',
    'proposals:review',
    'proposals:view_document',
    'proposals:view_handoff',
    'proposals:view_handoff_queue',
    'proposals:acknowledge_handoff',
    // Outros módulos
    'documents:view',
    'documents:upload',
    'documents:download',
    'documents:register_reference',
    'documents:view_requirements',
    'documents:fulfill_requirements',
    'documents:review_requirements',
    'documents:share',
    'documents:export',
    'surveys_and_visits:view',
    'surveys_and_visits:schedule',
    'schedule:view',
    'personal_account:view_profile',
    'personal_account:manage_preferences',
  ],

  // Financeiro (Gestão financeira e consulta operacional)
  finance: [
    'organization:view_overview',
    'finance:view_overview',
    'finance:view_records',
    'finance:manage_operations',
    'clients:view',
    'properties:view',
    'proposals:view',
    'proposals:view_financials',
    'proposals:view_document',
    'proposals:view_commercial_tracking',
    'proposals:view_handoff',
    'proposals:view_handoff_queue',
    'proposals:acknowledge_handoff',
    'documents:view',
    'documents:download',
    'documents:export',
    'personal_account:view_profile',
    'personal_account:manage_preferences',
  ],

  // Captador (Prospecção de produtores e referências documentais preliminares)
  capturer: [
    'organization:view_overview',
    'clients:view',
    'clients:create',
    'client_capturer_assignments:view',
    'properties:view',
    'properties:create',
    'properties:edit',
    'properties:geospatial:view',
    // Módulo 004: Solicitações de Laudo e Acompanhamento de Status
    'appraisal_requests:create',
    'appraisal_requests:view_related',
    'appraisal_requests:upload_documents',
    'appraisals:view_status_related',
    // Módulo 005: Prospecção, Elaboração Própria, Apresentação e Decisão
    'proposals:view',
    'proposals:view_related',
    'proposals:view_financials',
    'proposals:create',
    'proposals:edit_draft',
    'proposals:submit',
    'proposals:present',
    'proposals:record_decision',
    'proposals:cancel',
    'proposals:view_document',
    'proposals:issue_document',
    'proposals:view_commercial_tracking',
    'proposals:manage_follow_up',
    'proposals:view_handoff',
    'proposals:renew',
    // Outros módulos
    'documents:view',
    'documents:upload',
    'documents:download',
    'documents:register_reference',
    'documents:view_requirements',
    'documents:fulfill_requirements',
    'documents:share',
    'documents:export',
    'surveys_and_visits:view',
    'schedule:view',
    'personal_account:view_profile',
    'personal_account:manage_preferences',
  ],

  // Nenhum papel atribuído
  none: [],
};

export const ROLE_PERMISSIONS_SET_MAP: ReadonlyMap<AppRoleCode, ReadonlySet<Permission>> = new Map(
  Object.entries(ROLE_PERMISSIONS_MATRIX).map(([role, permissions]) => [
    role as AppRoleCode,
    new Set(permissions),
  ])
);

export function getRolePermissions(role: AppRoleCode): readonly Permission[] {
  return ROLE_PERMISSIONS_MATRIX[role] || [];
}
